/**
 * Motion Types Master List
 *
 * Comprehensive list of all motion types with complete metadata.
 * Organized by tier (A, B, C) and category.
 *
 * Count: 20 Tier A + 51 Tier B + 20 Tier C = 91 total
 * (Exceeds v6.3 spec minimum of 88)
 *
 * Source: Clay's v6.3 specification
 */

// ============================================================================
// TYPES
// ============================================================================

export interface MotionType {
  id: string;                      // Unique identifier, lowercase with underscores
  display_name: string;            // UI display name
  tier: 'A' | 'B' | 'C';          // Pricing tier
  category: MotionCategory;        // Grouping category
  availability: 'universal' | 'state_specific' | 'federal_only';
  available_states?: string[];     // For state_specific, which state codes
  court_types: ('state' | 'federal')[];
  description: string;             // Brief description for tooltip
  ccp_reference?: string;          // California Code of Civil Procedure reference
  frcp_reference?: string;         // Federal Rules reference
  base_price_min: number;          // Minimum price in cents
  base_price_max: number;          // Maximum price in cents
}

export type MotionCategory =
  | 'general'
  | 'service'
  | 'trial_setting'
  | 'case_management'
  | 'discovery'
  | 'discovery_sanctions'
  | 'pleading'
  | 'jurisdiction'
  | 'party_management'
  | 'settlement'
  | 'prejudgment'
  | 'trial'
  | 'post_judgment'
  | 'dispositive'
  | 'injunctive'
  | 'expert'
  | 'post_verdict';

export const CATEGORY_LABELS: Record<MotionCategory, string> = {
  general: 'General',
  service: 'Service of Process',
  trial_setting: 'Trial Setting',
  case_management: 'Case Management',
  discovery: 'Discovery',
  discovery_sanctions: 'Discovery Sanctions',
  pleading: 'Pleading',
  jurisdiction: 'Jurisdiction',
  party_management: 'Parties & Intervention',
  settlement: 'Settlement & ADR',
  prejudgment: 'Prejudgment',
  trial: 'Trial',
  post_judgment: 'Post-Judgment',
  dispositive: 'Dispositive',
  injunctive: 'Injunctive Relief',
  expert: 'Expert Witnesses',
  post_verdict: 'Post-Verdict',
};

export const TIER_LABELS: Record<'A' | 'B' | 'C', string> = {
  A: 'TIER A — Procedural ($150-$400)',
  B: 'TIER B — Intermediate ($500-$1,400)',
  C: 'TIER C — Complex/Dispositive ($1,500-$3,500)',
};

export const TIER_TURNAROUND: Record<'A' | 'B' | 'C', string> = {
  A: '2-3 business days',
  B: '3-4 business days',
  C: '4-5 business days',
};

// ============================================================================
// MOTION TYPES - ALL 91 MOTIONS (20 A + 51 B + 20 C)
// ============================================================================

export const MOTION_TYPES: MotionType[] = [
  // ============================================================================
  // TIER A — PROCEDURAL ($150-$400)
  // ============================================================================

  // General
  {
    id: 'motion_to_continue',
    display_name: 'Motion to Continue',
    tier: 'A',
    category: 'general',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to postpone a hearing, trial, or deadline',
    ccp_reference: 'CCP § 595',
    base_price_min: 15000,
    base_price_max: 25000,
  },
  {
    id: 'motion_to_consolidate',
    display_name: 'Motion to Consolidate',
    tier: 'A',
    category: 'case_management',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to combine related cases for efficiency',
    ccp_reference: 'CCP § 1048',
    frcp_reference: 'FRCP 42(a)',
    base_price_min: 20000,
    base_price_max: 35000,
  },
  {
    id: 'motion_for_leave_to_file',
    display_name: 'Motion for Leave to File',
    tier: 'A',
    category: 'pleading',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request permission to file a document (amended complaint, late filing, etc.)',
    base_price_min: 15000,
    base_price_max: 30000,
  },
  {
    id: 'motion_to_seal',
    display_name: 'Motion to Seal',
    tier: 'A',
    category: 'general',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to keep certain documents confidential',
    ccp_reference: 'CRC 2.550-2.551',
    base_price_min: 20000,
    base_price_max: 40000,
  },
  {
    id: 'motion_for_extension_of_time',
    display_name: 'Motion for Extension of Time',
    tier: 'A',
    category: 'general',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request additional time to meet a deadline',
    frcp_reference: 'FRCP 6(b)',
    base_price_min: 15000,
    base_price_max: 25000,
  },
  {
    id: 'motion_to_appear_pro_hac_vice',
    display_name: 'Motion to Appear Pro Hac Vice',
    tier: 'A',
    category: 'general',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request for out-of-state attorney to appear in case',
    base_price_min: 20000,
    base_price_max: 30000,
  },
  {
    id: 'motion_to_withdraw_as_counsel',
    display_name: 'Motion to Withdraw as Counsel',
    tier: 'A',
    category: 'general',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Attorney request to withdraw from representing client',
    ccp_reference: 'CCP § 284; CRC 3.1362',
    base_price_min: 15000,
    base_price_max: 25000,
  },
  {
    id: 'motion_for_relief_from_waiver',
    display_name: 'Motion for Relief from Waiver',
    tier: 'A',
    category: 'general',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to restore waived rights or objections',
    ccp_reference: 'CCP § 2031.300',
    base_price_min: 20000,
    base_price_max: 35000,
  },

  // Service of Process
  {
    id: 'motion_for_service_by_publication',
    display_name: 'Motion for Service by Publication',
    tier: 'A',
    category: 'service',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to serve defendant through newspaper publication',
    ccp_reference: 'CCP § 415.50',
    base_price_min: 20000,
    base_price_max: 35000,
  },
  {
    id: 'motion_for_alternative_service',
    display_name: 'Motion for Alternative Service',
    tier: 'A',
    category: 'service',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request for alternative method of service (email, posting, etc.)',
    ccp_reference: 'CCP § 415.30',
    base_price_min: 20000,
    base_price_max: 35000,
  },

  // Trial Setting
  {
    id: 'motion_to_set_trial',
    display_name: 'Motion to Set for Trial / Trial Setting Conference',
    tier: 'A',
    category: 'trial_setting',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to schedule trial date',
    ccp_reference: 'CCP § 594',
    base_price_min: 15000,
    base_price_max: 25000,
  },
  {
    id: 'motion_for_preference',
    display_name: 'Motion for Preference (Trial Priority)',
    tier: 'A',
    category: 'trial_setting',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request for expedited trial setting (elderly, health, etc.)',
    ccp_reference: 'CCP § 36',
    base_price_min: 25000,
    base_price_max: 40000,
  },

  // Case Management
  {
    id: 'motion_to_bifurcate',
    display_name: 'Motion to Bifurcate / Separate Trial',
    tier: 'A',
    category: 'case_management',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to try issues separately (liability/damages, etc.)',
    ccp_reference: 'CCP § 598',
    frcp_reference: 'FRCP 42(b)',
    base_price_min: 25000,
    base_price_max: 40000,
  },
  {
    id: 'motion_to_sever',
    display_name: 'Motion to Sever',
    tier: 'A',
    category: 'case_management',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to separate claims or parties into different cases',
    frcp_reference: 'FRCP 21',
    base_price_min: 25000,
    base_price_max: 40000,
  },
  {
    id: 'motion_relate_cases',
    display_name: 'Motion to Relate Cases',
    tier: 'A',
    category: 'case_management',
    availability: 'state_specific',
    available_states: ['CA'],
    court_types: ['state'],
    description: 'Notice that cases involve common questions (California)',
    ccp_reference: 'CRC 3.300',
    base_price_min: 15000,
    base_price_max: 25000,
  },
  {
    id: 'motion_complex_case_determination',
    display_name: 'Motion for Complex Case Determination',
    tier: 'A',
    category: 'case_management',
    availability: 'state_specific',
    available_states: ['CA'],
    court_types: ['state'],
    description: 'Request to designate case as complex litigation (California)',
    ccp_reference: 'CRC 3.400',
    base_price_min: 25000,
    base_price_max: 40000,
  },
  {
    id: 'motion_for_telephonic_appearance',
    display_name: 'Motion for Telephonic/Video Appearance',
    tier: 'A',
    category: 'general',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to appear remotely at hearing',
    base_price_min: 15000,
    base_price_max: 25000,
  },

  // ============================================================================
  // TIER B — INTERMEDIATE ($500-$1,400)
  // ============================================================================

  // Discovery
  {
    id: 'motion_to_compel_discovery',
    display_name: 'Motion to Compel Discovery Responses',
    tier: 'B',
    category: 'discovery',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to force party to respond to discovery requests',
    ccp_reference: 'CCP § 2030.300, 2031.300, 2033.280',
    frcp_reference: 'FRCP 37(a)',
    base_price_min: 50000,
    base_price_max: 90000,
  },
  {
    id: 'motion_to_compel_further',
    display_name: 'Motion to Compel Further Discovery Responses',
    tier: 'B',
    category: 'discovery',
    availability: 'state_specific',
    available_states: ['CA'],
    court_types: ['state'],
    description: 'Request for more complete discovery responses (California)',
    ccp_reference: 'CCP § 2030.300, 2031.310',
    base_price_min: 60000,
    base_price_max: 100000,
  },
  {
    id: 'motion_to_compel_deposition',
    display_name: 'Motion to Compel Deposition',
    tier: 'B',
    category: 'discovery',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to force witness to appear for deposition',
    ccp_reference: 'CCP § 2025.450',
    frcp_reference: 'FRCP 37(a)(3)(B)',
    base_price_min: 50000,
    base_price_max: 85000,
  },
  {
    id: 'motion_for_protective_order',
    display_name: 'Motion for Protective Order',
    tier: 'B',
    category: 'discovery',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to limit or prevent discovery',
    ccp_reference: 'CCP § 2030.090, 2031.060',
    frcp_reference: 'FRCP 26(c)',
    base_price_min: 60000,
    base_price_max: 100000,
  },
  {
    id: 'motion_to_quash_subpoena',
    display_name: 'Motion to Quash Subpoena (Discovery)',
    tier: 'B',
    category: 'discovery',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to invalidate discovery subpoena',
    ccp_reference: 'CCP § 1987.1',
    frcp_reference: 'FRCP 45(d)(3)',
    base_price_min: 50000,
    base_price_max: 85000,
  },
  {
    id: 'motion_to_deem_admitted',
    display_name: 'Motion to Deem Requests for Admission Admitted',
    tier: 'B',
    category: 'discovery',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to have unanswered RFAs deemed admitted',
    ccp_reference: 'CCP § 2033.280',
    frcp_reference: 'FRCP 36(a)(3)',
    base_price_min: 45000,
    base_price_max: 75000,
  },

  // Discovery Sanctions
  {
    id: 'motion_for_discovery_sanctions',
    display_name: 'Motion for Discovery Sanctions',
    tier: 'B',
    category: 'discovery_sanctions',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request for penalties due to discovery abuse',
    ccp_reference: 'CCP § 2023.030',
    frcp_reference: 'FRCP 37(b)',
    base_price_min: 60000,
    base_price_max: 100000,
  },
  {
    id: 'motion_for_terminating_sanctions',
    display_name: 'Motion for Terminating Sanctions',
    tier: 'B',
    category: 'discovery_sanctions',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to dismiss case or strike answer due to discovery abuse',
    ccp_reference: 'CCP § 2023.030(d)',
    frcp_reference: 'FRCP 37(b)(2)(A)',
    base_price_min: 80000,
    base_price_max: 140000,
  },
  {
    id: 'motion_for_issue_sanctions',
    display_name: 'Motion for Issue/Evidence Sanctions',
    tier: 'B',
    category: 'discovery_sanctions',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request for adverse findings due to discovery abuse',
    ccp_reference: 'CCP § 2023.030(b)-(c)',
    frcp_reference: 'FRCP 37(b)(2)(A)',
    base_price_min: 70000,
    base_price_max: 120000,
  },

  // Pleading
  {
    id: 'demurrer',
    display_name: 'Demurrer',
    tier: 'B',
    category: 'pleading',
    availability: 'state_specific',
    available_states: ['CA'],
    court_types: ['state'],
    description: 'Challenge to legal sufficiency of pleading (California)',
    ccp_reference: 'CCP § 430.10-430.80',
    base_price_min: 70000,
    base_price_max: 120000,
  },
  {
    id: 'motion_to_strike',
    display_name: 'Motion to Strike',
    tier: 'B',
    category: 'pleading',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to remove irrelevant, false, or improper matter from pleading',
    ccp_reference: 'CCP § 435-436',
    frcp_reference: 'FRCP 12(f)',
    base_price_min: 50000,
    base_price_max: 90000,
  },
  {
    id: 'motion_for_judgment_on_pleadings',
    display_name: 'Motion for Judgment on the Pleadings',
    tier: 'B',
    category: 'pleading',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request for judgment based on pleadings alone',
    ccp_reference: 'CCP § 438',
    frcp_reference: 'FRCP 12(c)',
    base_price_min: 70000,
    base_price_max: 120000,
  },
  {
    id: 'motion_to_amend_complaint',
    display_name: 'Motion for Leave to Amend Complaint',
    tier: 'B',
    category: 'pleading',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to modify complaint after deadline',
    ccp_reference: 'CCP § 473',
    frcp_reference: 'FRCP 15(a)(2)',
    base_price_min: 50000,
    base_price_max: 85000,
  },

  // Jurisdiction
  {
    id: 'motion_to_quash_service',
    display_name: 'Motion to Quash Service of Summons',
    tier: 'B',
    category: 'jurisdiction',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Challenge to personal jurisdiction or improper service',
    ccp_reference: 'CCP § 418.10',
    frcp_reference: 'FRCP 12(b)(2), 12(b)(5)',
    base_price_min: 60000,
    base_price_max: 100000,
  },
  {
    id: 'motion_to_transfer_venue',
    display_name: 'Motion to Change/Transfer Venue',
    tier: 'B',
    category: 'jurisdiction',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to move case to different court location',
    ccp_reference: 'CCP § 397',
    frcp_reference: '28 U.S.C. § 1404',
    base_price_min: 60000,
    base_price_max: 100000,
  },
  {
    id: 'motion_to_remand',
    display_name: 'Motion to Remand',
    tier: 'B',
    category: 'jurisdiction',
    availability: 'federal_only',
    court_types: ['federal'],
    description: 'Request to return removed case to state court',
    frcp_reference: '28 U.S.C. § 1447',
    base_price_min: 70000,
    base_price_max: 120000,
  },
  {
    id: 'motion_to_stay_pending_arbitration',
    display_name: 'Motion to Stay Pending Arbitration',
    tier: 'B',
    category: 'jurisdiction',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to pause litigation while arbitration proceeds',
    ccp_reference: 'CCP § 1281.4',
    frcp_reference: '9 U.S.C. § 3',
    base_price_min: 60000,
    base_price_max: 100000,
  },
  {
    id: 'motion_to_compel_arbitration',
    display_name: 'Motion to Compel Arbitration',
    tier: 'B',
    category: 'jurisdiction',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to enforce arbitration agreement',
    ccp_reference: 'CCP § 1281.2',
    frcp_reference: '9 U.S.C. § 4',
    base_price_min: 70000,
    base_price_max: 120000,
  },

  // Parties & Intervention
  {
    id: 'motion_to_intervene',
    display_name: 'Motion to Intervene',
    tier: 'B',
    category: 'party_management',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request by non-party to join lawsuit',
    ccp_reference: 'CCP § 387',
    frcp_reference: 'FRCP 24',
    base_price_min: 70000,
    base_price_max: 120000,
  },
  {
    id: 'motion_to_substitute_party',
    display_name: 'Motion to Substitute Party',
    tier: 'B',
    category: 'party_management',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to replace party (death, transfer of interest, etc.)',
    ccp_reference: 'CCP § 377.31',
    frcp_reference: 'FRCP 25',
    base_price_min: 45000,
    base_price_max: 75000,
  },
  {
    id: 'motion_to_add_party',
    display_name: 'Motion to Add Party / Amend to Add Doe Defendant',
    tier: 'B',
    category: 'party_management',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to add additional party to lawsuit',
    ccp_reference: 'CCP § 474',
    frcp_reference: 'FRCP 20, 21',
    base_price_min: 50000,
    base_price_max: 85000,
  },

  // Settlement & ADR
  {
    id: 'motion_to_enforce_settlement',
    display_name: 'Motion to Enforce Settlement',
    tier: 'B',
    category: 'settlement',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to compel compliance with settlement agreement',
    ccp_reference: 'CCP § 664.6',
    base_price_min: 60000,
    base_price_max: 100000,
  },
  {
    id: 'motion_for_good_faith_settlement',
    display_name: 'Motion for Good Faith Settlement Determination',
    tier: 'B',
    category: 'settlement',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request for finding that partial settlement was in good faith',
    ccp_reference: 'CCP § 877.6',
    base_price_min: 60000,
    base_price_max: 100000,
  },

  // Prejudgment
  {
    id: 'motion_expunge_lis_pendens',
    display_name: 'Motion to Expunge Lis Pendens',
    tier: 'B',
    category: 'prejudgment',
    availability: 'state_specific',
    available_states: ['CA'],
    court_types: ['state'],
    description: 'Request to remove notice of pending action on property (California)',
    ccp_reference: 'CCP § 405.30-405.32',
    base_price_min: 60000,
    base_price_max: 100000,
  },
  {
    id: 'motion_for_attachment',
    display_name: 'Motion for Attachment / Writ of Attachment',
    tier: 'B',
    category: 'prejudgment',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to seize defendant\'s assets before judgment',
    ccp_reference: 'CCP § 484.010-484.090',
    base_price_min: 70000,
    base_price_max: 120000,
  },
  {
    id: 'motion_for_claim_and_delivery',
    display_name: 'Motion for Claim and Delivery',
    tier: 'B',
    category: 'prejudgment',
    availability: 'universal',
    court_types: ['state'],
    description: 'Request for possession of specific personal property',
    ccp_reference: 'CCP § 511.010-512.070',
    base_price_min: 60000,
    base_price_max: 100000,
  },

  // Trial
  {
    id: 'motion_in_limine_simple',
    display_name: 'Motion in Limine (Simple)',
    tier: 'B',
    category: 'trial',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Pre-trial motion to exclude evidence (straightforward issues)',
    base_price_min: 50000,
    base_price_max: 90000,
  },
  {
    id: 'motion_for_directed_verdict',
    display_name: 'Motion for Directed Verdict / JMOL',
    tier: 'B',
    category: 'trial',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Mid-trial request for judgment (no evidence supports claim)',
    ccp_reference: 'CCP § 630',
    frcp_reference: 'FRCP 50(a)',
    base_price_min: 70000,
    base_price_max: 120000,
  },
  {
    id: 'motion_for_mistrial',
    display_name: 'Motion for Mistrial',
    tier: 'B',
    category: 'trial',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to declare trial void due to error or misconduct',
    base_price_min: 60000,
    base_price_max: 100000,
  },

  // Post-Judgment
  {
    id: 'motion_for_new_trial',
    display_name: 'Motion for New Trial',
    tier: 'B',
    category: 'post_judgment',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to retry case due to errors or new evidence',
    ccp_reference: 'CCP § 657',
    frcp_reference: 'FRCP 59(a)',
    base_price_min: 80000,
    base_price_max: 140000,
  },
  {
    id: 'motion_to_set_aside_default',
    display_name: 'Motion to Set Aside Default / Vacate Judgment',
    tier: 'B',
    category: 'post_judgment',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to undo default judgment',
    ccp_reference: 'CCP § 473(b), 473.5',
    frcp_reference: 'FRCP 55(c), 60(b)',
    base_price_min: 60000,
    base_price_max: 100000,
  },
  {
    id: 'motion_for_attorneys_fees',
    display_name: 'Motion for Attorney\'s Fees',
    tier: 'B',
    category: 'post_judgment',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request for fee award after favorable judgment',
    ccp_reference: 'CCP § 1033.5',
    frcp_reference: 'FRCP 54(d)(2)',
    base_price_min: 60000,
    base_price_max: 100000,
  },
  {
    id: 'motion_to_tax_costs',
    display_name: 'Motion to Tax/Strike Costs',
    tier: 'B',
    category: 'post_judgment',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Challenge to claimed litigation costs',
    ccp_reference: 'CCP § 1034',
    frcp_reference: 'FRCP 54(d)(1)',
    base_price_min: 45000,
    base_price_max: 75000,
  },

  // Federal-Only Motions (Tier B)
  {
    id: 'motion_to_dismiss_12b6',
    display_name: 'Motion to Dismiss (12(b)(6))',
    tier: 'B',
    category: 'dispositive',
    availability: 'federal_only',
    court_types: ['federal'],
    description: 'Federal motion to dismiss for failure to state a claim',
    frcp_reference: 'FRCP 12(b)(6)',
    base_price_min: 80000,
    base_price_max: 140000,
  },

  // Louisiana-Specific Exceptions (Tier B)
  {
    id: 'exception_no_cause_of_action',
    display_name: 'Exception of No Cause of Action',
    tier: 'B',
    category: 'pleading',
    availability: 'state_specific',
    available_states: ['LA'],
    court_types: ['state'],
    description: 'Louisiana equivalent of demurrer - challenges legal sufficiency',
    base_price_min: 70000,
    base_price_max: 120000,
  },
  {
    id: 'exception_prescription',
    display_name: 'Exception of Prescription',
    tier: 'B',
    category: 'pleading',
    availability: 'state_specific',
    available_states: ['LA'],
    court_types: ['state'],
    description: 'Louisiana statute of limitations defense',
    base_price_min: 60000,
    base_price_max: 100000,
  },
  {
    id: 'exception_no_right_of_action',
    display_name: 'Exception of No Right of Action',
    tier: 'B',
    category: 'pleading',
    availability: 'state_specific',
    available_states: ['LA'],
    court_types: ['state'],
    description: 'Louisiana challenge to plaintiff\'s standing',
    base_price_min: 60000,
    base_price_max: 100000,
  },
  {
    id: 'declinatory_exception',
    display_name: 'Declinatory Exception',
    tier: 'B',
    category: 'jurisdiction',
    availability: 'state_specific',
    available_states: ['LA'],
    court_types: ['state'],
    description: 'Louisiana jurisdiction/venue/lis pendens objection',
    base_price_min: 60000,
    base_price_max: 100000,
  },
  {
    id: 'dilatory_exception',
    display_name: 'Dilatory Exception',
    tier: 'B',
    category: 'pleading',
    availability: 'state_specific',
    available_states: ['LA'],
    court_types: ['state'],
    description: 'Louisiana pleading defect objection',
    base_price_min: 50000,
    base_price_max: 85000,
  },
  {
    id: 'peremptory_exception',
    display_name: 'Peremptory Exception',
    tier: 'B',
    category: 'pleading',
    availability: 'state_specific',
    available_states: ['LA'],
    court_types: ['state'],
    description: 'Louisiana dispositive pleading challenge',
    base_price_min: 70000,
    base_price_max: 120000,
  },

  // Additional Tier B Motions
  {
    id: 'motion_for_default_judgment',
    display_name: 'Motion for Default Judgment',
    tier: 'B',
    category: 'post_judgment',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request for judgment against non-appearing defendant',
    ccp_reference: 'CCP § 585',
    frcp_reference: 'FRCP 55(b)',
    base_price_min: 50000,
    base_price_max: 85000,
  },
  {
    id: 'motion_to_amend_answer',
    display_name: 'Motion for Leave to Amend Answer',
    tier: 'B',
    category: 'pleading',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to modify answer or affirmative defenses',
    frcp_reference: 'FRCP 15(a)(2)',
    base_price_min: 50000,
    base_price_max: 85000,
  },
  {
    id: 'motion_for_reconsideration',
    display_name: 'Motion for Reconsideration',
    tier: 'B',
    category: 'post_judgment',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to revisit previous court order',
    ccp_reference: 'CCP § 1008',
    base_price_min: 60000,
    base_price_max: 100000,
  },
  {
    id: 'motion_to_compel_ime',
    display_name: 'Motion to Compel Independent Medical Exam',
    tier: 'B',
    category: 'discovery',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to require physical/mental examination',
    ccp_reference: 'CCP § 2032.310',
    frcp_reference: 'FRCP 35',
    base_price_min: 60000,
    base_price_max: 100000,
  },
  {
    id: 'motion_to_extend_discovery',
    display_name: 'Motion to Extend Discovery Deadlines',
    tier: 'B',
    category: 'discovery',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request for additional time to complete discovery',
    base_price_min: 45000,
    base_price_max: 75000,
  },
  {
    id: 'motion_to_withdraw_admission',
    display_name: 'Motion to Withdraw/Amend Admission',
    tier: 'B',
    category: 'discovery',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to withdraw or modify response to RFA',
    ccp_reference: 'CCP § 2033.300',
    frcp_reference: 'FRCP 36(b)',
    base_price_min: 50000,
    base_price_max: 85000,
  },
  {
    id: 'motion_for_costs',
    display_name: 'Motion for Costs',
    tier: 'B',
    category: 'post_judgment',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request for litigation costs after judgment',
    ccp_reference: 'CCP § 1032',
    frcp_reference: 'FRCP 54(d)',
    base_price_min: 45000,
    base_price_max: 75000,
  },
  {
    id: 'motion_for_stay_execution',
    display_name: 'Motion for Stay of Execution',
    tier: 'B',
    category: 'post_judgment',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to delay enforcement of judgment',
    ccp_reference: 'CCP § 918',
    frcp_reference: 'FRCP 62',
    base_price_min: 60000,
    base_price_max: 100000,
  },
  {
    id: 'motion_for_leave_amicus',
    display_name: 'Motion for Leave to File Amicus Brief',
    tier: 'B',
    category: 'general',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request for non-party to submit friend of court brief',
    frcp_reference: 'FRAP 29',
    base_price_min: 50000,
    base_price_max: 90000,
  },
  {
    id: 'motion_correct_clerical_error',
    display_name: 'Motion to Correct Clerical Error',
    tier: 'B',
    category: 'post_judgment',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to fix clerical mistakes in judgment',
    ccp_reference: 'CCP § 473(d)',
    frcp_reference: 'FRCP 60(a)',
    base_price_min: 45000,
    base_price_max: 75000,
  },
  {
    id: 'motion_to_dismiss_simple',
    display_name: 'Motion to Dismiss (Simple/Procedural)',
    tier: 'B',
    category: 'pleading',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Motion to dismiss on single straightforward ground',
    frcp_reference: 'FRCP 12(b)',
    base_price_min: 60000,
    base_price_max: 100000,
  },

  // ============================================================================
  // TIER C — COMPLEX/DISPOSITIVE ($1,500-$3,500)
  // ============================================================================

  // Dispositive
  {
    id: 'motion_summary_judgment',
    display_name: 'Motion for Summary Judgment (MSJ)',
    tier: 'C',
    category: 'dispositive',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request for judgment without trial - no disputed material facts',
    ccp_reference: 'CCP § 437c',
    frcp_reference: 'FRCP 56',
    base_price_min: 150000,
    base_price_max: 300000,
  },
  {
    id: 'motion_for_summary_adjudication',
    display_name: 'Motion for Summary Adjudication (MSA)',
    tier: 'C',
    category: 'dispositive',
    availability: 'state_specific',
    available_states: ['CA'],
    court_types: ['state'],
    description: 'Summary judgment on specific issues/causes of action (California)',
    ccp_reference: 'CCP § 437c(f)',
    base_price_min: 150000,
    base_price_max: 280000,
  },
  {
    id: 'opposition_msj',
    display_name: 'Opposition to Motion for Summary Judgment',
    tier: 'C',
    category: 'dispositive',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Response opposing summary judgment motion',
    ccp_reference: 'CCP § 437c',
    frcp_reference: 'FRCP 56',
    base_price_min: 150000,
    base_price_max: 300000,
  },
  {
    id: 'motion_to_dismiss_dispositive',
    display_name: 'Motion to Dismiss (Dispositive/Complex)',
    tier: 'C',
    category: 'dispositive',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Complex motion to dismiss with multiple grounds',
    base_price_min: 150000,
    base_price_max: 250000,
  },

  // Anti-SLAPP
  {
    id: 'anti_slapp',
    display_name: 'Anti-SLAPP Motion (Special Motion to Strike)',
    tier: 'C',
    category: 'dispositive',
    availability: 'state_specific',
    available_states: ['CA', 'CO', 'DC', 'FL', 'GA', 'HI', 'IL', 'IN', 'KS', 'KY', 'ME', 'MD', 'MA', 'MI', 'MN', 'MO', 'NE', 'NV', 'NJ', 'NM', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA'],
    court_types: ['state'],
    description: 'Motion to strike claims arising from protected speech/petition activity',
    ccp_reference: 'CCP § 425.16',
    base_price_min: 180000,
    base_price_max: 350000,
  },
  {
    id: 'opposition_anti_slapp',
    display_name: 'Opposition to Anti-SLAPP Motion',
    tier: 'C',
    category: 'dispositive',
    availability: 'state_specific',
    available_states: ['CA', 'CO', 'DC', 'FL', 'GA', 'HI', 'IL', 'IN', 'KS', 'KY', 'ME', 'MD', 'MA', 'MI', 'MN', 'MO', 'NE', 'NV', 'NJ', 'NM', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA'],
    court_types: ['state'],
    description: 'Opposition to anti-SLAPP motion',
    ccp_reference: 'CCP § 425.16',
    base_price_min: 180000,
    base_price_max: 350000,
  },

  // California-Specific Complex
  {
    id: 'peremptory_challenge_170_6',
    display_name: 'Peremptory Challenge (CCP § 170.6)',
    tier: 'C',
    category: 'trial',
    availability: 'state_specific',
    available_states: ['CA'],
    court_types: ['state'],
    description: 'One-time automatic judicial disqualification (California)',
    ccp_reference: 'CCP § 170.6',
    base_price_min: 150000,
    base_price_max: 200000,
  },
  {
    id: 'motion_bifurcate_punitive_damages',
    display_name: 'Motion to Bifurcate Punitive Damages',
    tier: 'C',
    category: 'trial',
    availability: 'state_specific',
    available_states: ['CA'],
    court_types: ['state'],
    description: 'Separate punitive damages phase (California)',
    ccp_reference: 'Civil Code § 3295(d)',
    base_price_min: 150000,
    base_price_max: 250000,
  },

  // Injunctive Relief
  {
    id: 'motion_preliminary_injunction',
    display_name: 'Motion for Preliminary Injunction',
    tier: 'C',
    category: 'injunctive',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request for temporary court order during litigation',
    ccp_reference: 'CCP § 526',
    frcp_reference: 'FRCP 65',
    base_price_min: 200000,
    base_price_max: 350000,
  },
  {
    id: 'motion_tro',
    display_name: 'Motion for Temporary Restraining Order (TRO)',
    tier: 'C',
    category: 'injunctive',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Emergency request for immediate court order',
    ccp_reference: 'CCP § 527',
    frcp_reference: 'FRCP 65(b)',
    base_price_min: 200000,
    base_price_max: 350000,
  },
  {
    id: 'opposition_preliminary_injunction',
    display_name: 'Opposition to Preliminary Injunction',
    tier: 'C',
    category: 'injunctive',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Opposition to preliminary injunction motion',
    ccp_reference: 'CCP § 526',
    frcp_reference: 'FRCP 65',
    base_price_min: 180000,
    base_price_max: 320000,
  },
  {
    id: 'motion_to_dissolve_injunction',
    display_name: 'Motion to Dissolve/Modify Injunction',
    tier: 'C',
    category: 'injunctive',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to remove or change existing injunction',
    ccp_reference: 'CCP § 533',
    frcp_reference: 'FRCP 62.1',
    base_price_min: 150000,
    base_price_max: 250000,
  },

  // Expert Witnesses
  {
    id: 'daubert_motion',
    display_name: 'Daubert Motion (Expert Exclusion)',
    tier: 'C',
    category: 'expert',
    availability: 'federal_only',
    court_types: ['federal'],
    description: 'Motion to exclude expert testimony (federal reliability standard)',
    frcp_reference: 'FRE 702; Daubert v. Merrell Dow',
    base_price_min: 200000,
    base_price_max: 350000,
  },
  {
    id: 'motion_in_limine_complex',
    display_name: 'Motion in Limine (Complex/Daubert-Style)',
    tier: 'C',
    category: 'expert',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Complex pre-trial evidence motion (expert qualification, scientific evidence)',
    base_price_min: 150000,
    base_price_max: 280000,
  },
  {
    id: 'sargon_motion',
    display_name: 'Sargon Motion (California Expert Challenge)',
    tier: 'C',
    category: 'expert',
    availability: 'state_specific',
    available_states: ['CA'],
    court_types: ['state'],
    description: 'California expert testimony challenge (Sargon standard)',
    ccp_reference: 'Evidence Code § 801; Sargon v. USC',
    base_price_min: 180000,
    base_price_max: 320000,
  },

  // Post-Verdict
  {
    id: 'motion_jnov',
    display_name: 'Motion for JNOV / Renewed JMOL',
    tier: 'C',
    category: 'post_verdict',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Post-verdict request for judgment notwithstanding verdict',
    ccp_reference: 'CCP § 629',
    frcp_reference: 'FRCP 50(b)',
    base_price_min: 180000,
    base_price_max: 320000,
  },
  {
    id: 'motion_for_remittitur',
    display_name: 'Motion for Remittitur / Additur',
    tier: 'C',
    category: 'post_verdict',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to reduce (or increase in state court) damages award',
    ccp_reference: 'CCP § 662.5',
    base_price_min: 150000,
    base_price_max: 280000,
  },

  // Class Action
  {
    id: 'motion_class_certification',
    display_name: 'Motion for Class Certification',
    tier: 'C',
    category: 'party_management',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to certify case as class action',
    ccp_reference: 'CCP § 382',
    frcp_reference: 'FRCP 23',
    base_price_min: 250000,
    base_price_max: 350000,
  },
  {
    id: 'opposition_class_certification',
    display_name: 'Opposition to Class Certification',
    tier: 'C',
    category: 'party_management',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Opposition to class certification motion',
    ccp_reference: 'CCP § 382',
    frcp_reference: 'FRCP 23',
    base_price_min: 250000,
    base_price_max: 350000,
  },
  {
    id: 'motion_to_decertify_class',
    display_name: 'Motion to Decertify Class',
    tier: 'C',
    category: 'party_management',
    availability: 'universal',
    court_types: ['state', 'federal'],
    description: 'Request to undo class certification',
    frcp_reference: 'FRCP 23(c)(1)',
    base_price_min: 200000,
    base_price_max: 320000,
  },
];

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Get motion type by ID
 */
export function getMotionType(id: string): MotionType | undefined {
  return MOTION_TYPES.find((motion) => motion.id === id);
}

/**
 * Get motions by tier
 */
export function getMotionsByTier(tier: 'A' | 'B' | 'C'): MotionType[] {
  return MOTION_TYPES.filter((motion) => motion.tier === tier);
}

/**
 * Get motions by category
 */
export function getMotionsByCategory(category: MotionCategory): MotionType[] {
  return MOTION_TYPES.filter((motion) => motion.category === category);
}

/**
 * Get all categories that have motions
 */
export function getActiveCategories(): MotionCategory[] {
  const categories = new Set<MotionCategory>();
  MOTION_TYPES.forEach((motion) => categories.add(motion.category));
  return Array.from(categories);
}

/**
 * Get price range for a tier
 */
export function getTierPriceRange(tier: 'A' | 'B' | 'C'): { min: number; max: number } {
  const motions = getMotionsByTier(tier);
  if (motions.length === 0) return { min: 0, max: 0 };

  return {
    min: Math.min(...motions.map((m) => m.base_price_min)),
    max: Math.max(...motions.map((m) => m.base_price_max)),
  };
}
