'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import {
  CheckCircle2,
  XCircle,
  RotateCcw,
  Loader2,
  AlertTriangle,
  Send,
  FileCheck,
} from 'lucide-react';

interface MotionApprovalPanelProps {
  orderId: string;
  orderNumber: string;
  clientName?: string;
  hasDeliverable: boolean;
}

type ApprovalAction = 'approve' | 'reject' | 'request_revision';

export function MotionApprovalPanel({
  orderId,
  orderNumber,
  clientName,
  hasDeliverable,
}: MotionApprovalPanelProps) {
  const router = useRouter();
  const [action, setAction] = useState<ApprovalAction | null>(null);
  const [feedback, setFeedback] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async () => {
    if (!action) return;
    if ((action === 'reject' || action === 'request_revision') && !feedback.trim()) {
      setError('Please provide feedback for rejection or revision request.');
      return;
    }

    setIsSubmitting(true);
    setError(null);

    try {
      const response = await fetch('/api/workflow/approve', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          orderId,
          action,
          feedback: feedback.trim() || undefined,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to process approval');
      }

      // Refresh the page to show updated status
      router.refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to process approval');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Card className="bg-amber-50 border-amber-200 shadow-lg">
      <CardHeader className="border-b border-amber-200 bg-amber-100/50">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-amber-200 rounded-lg">
            <AlertTriangle className="h-5 w-5 text-amber-700" />
          </div>
          <div>
            <CardTitle className="text-lg text-amber-900">Review Required</CardTitle>
            <CardDescription className="text-amber-700">
              AI-generated draft ready for your approval
            </CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent className="p-6 space-y-4">
        {!hasDeliverable && (
          <div className="p-3 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm">
            <strong>Warning:</strong> No deliverable PDF found. The motion may not have been generated correctly.
          </div>
        )}

        <p className="text-sm text-amber-800">
          This motion was generated by AI and is awaiting your review before being sent to{' '}
          <strong>{clientName || 'the client'}</strong>.
        </p>

        {/* Action Buttons */}
        <div className="grid gap-3 sm:grid-cols-3">
          <Button
            variant={action === 'approve' ? 'default' : 'outline'}
            className={`h-auto py-4 flex-col gap-2 ${
              action === 'approve'
                ? 'bg-green-600 hover:bg-green-700 text-white border-green-600'
                : 'border-green-300 text-green-700 hover:bg-green-50 hover:border-green-400'
            }`}
            onClick={() => {
              setAction('approve');
              setFeedback('');
            }}
            disabled={isSubmitting}
          >
            <CheckCircle2 className="h-6 w-6" />
            <span className="font-semibold">Approve</span>
            <span className="text-xs opacity-80">Send to client</span>
          </Button>

          <Button
            variant={action === 'request_revision' ? 'default' : 'outline'}
            className={`h-auto py-4 flex-col gap-2 ${
              action === 'request_revision'
                ? 'bg-orange-600 hover:bg-orange-700 text-white border-orange-600'
                : 'border-orange-300 text-orange-700 hover:bg-orange-50 hover:border-orange-400'
            }`}
            onClick={() => setAction('request_revision')}
            disabled={isSubmitting}
          >
            <RotateCcw className="h-6 w-6" />
            <span className="font-semibold">Request Revision</span>
            <span className="text-xs opacity-80">Needs changes</span>
          </Button>

          <Button
            variant={action === 'reject' ? 'default' : 'outline'}
            className={`h-auto py-4 flex-col gap-2 ${
              action === 'reject'
                ? 'bg-red-600 hover:bg-red-700 text-white border-red-600'
                : 'border-red-300 text-red-700 hover:bg-red-50 hover:border-red-400'
            }`}
            onClick={() => setAction('reject')}
            disabled={isSubmitting}
          >
            <XCircle className="h-6 w-6" />
            <span className="font-semibold">Reject</span>
            <span className="text-xs opacity-80">Re-generate</span>
          </Button>
        </div>

        {/* Feedback field for reject/revision */}
        {(action === 'reject' || action === 'request_revision') && (
          <div className="space-y-2 animate-in fade-in slide-in-from-top-2 duration-200">
            <Label htmlFor="feedback" className="text-amber-900">
              {action === 'reject' ? 'Rejection Reason' : 'Revision Instructions'} *
            </Label>
            <Textarea
              id="feedback"
              placeholder={
                action === 'reject'
                  ? 'Explain why this draft is being rejected...'
                  : 'Describe what changes are needed...'
              }
              value={feedback}
              onChange={(e) => setFeedback(e.target.value)}
              className="min-h-[100px] border-amber-300 focus:border-amber-500"
            />
          </div>
        )}

        {/* Error message */}
        {error && (
          <div className="p-3 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm">
            {error}
          </div>
        )}

        {/* Submit Button */}
        {action && (
          <div className="flex justify-end pt-2">
            <Button
              onClick={handleSubmit}
              disabled={isSubmitting || ((action === 'reject' || action === 'request_revision') && !feedback.trim())}
              className={`px-6 ${
                action === 'approve'
                  ? 'bg-green-600 hover:bg-green-700'
                  : action === 'request_revision'
                  ? 'bg-orange-600 hover:bg-orange-700'
                  : 'bg-red-600 hover:bg-red-700'
              }`}
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Processing...
                </>
              ) : action === 'approve' ? (
                <>
                  <Send className="h-4 w-4 mr-2" />
                  Approve & Send to Client
                </>
              ) : action === 'request_revision' ? (
                <>
                  <RotateCcw className="h-4 w-4 mr-2" />
                  Submit Revision Request
                </>
              ) : (
                <>
                  <XCircle className="h-4 w-4 mr-2" />
                  Reject & Re-generate
                </>
              )}
            </Button>
          </div>
        )}

        {/* Approve confirmation */}
        {action === 'approve' && (
          <p className="text-xs text-amber-700 text-center">
            <FileCheck className="h-3 w-3 inline mr-1" />
            The client will receive an email notification when approved.
          </p>
        )}
      </CardContent>
    </Card>
  );
}
