-- Delta Resolution: Expand orders status CHECK constraint
-- D4-CORR-001 + v5-XDC-012: Adds PENDING_CONFLICT_REVIEW, DISPUTED, REFUNDED, UPGRADE_PENDING
-- DB uses flat CANCELLED (toDbStatus maps CANCELLED_USER/SYSTEM/CONFLICT → CANCELLED)
-- DB uses REVISION_REQ (toDbStatus maps REVISION_REQUESTED → REVISION_REQ)

ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_status_check;
ALTER TABLE orders ADD CONSTRAINT orders_status_check CHECK (
  status IN (
    'INTAKE', 'PROCESSING', 'AWAITING_OPUS', 'HOLD_PENDING',
    'PROTOCOL_10_EXIT', 'UPGRADE_PENDING', 'PENDING_CONFLICT_REVIEW',
    'AWAITING_APPROVAL', 'REVISION_REQ', 'COMPLETED',
    'CANCELLED', 'DISPUTED', 'REFUNDED', 'FAILED'
  )
);
