-- ============================================================================
-- D6 C-006: delivery_packages DDL — Add D8-expected columns
-- Date: 2026-02-16
--
-- D6 owns table creation/schema. D8 owns writes to these columns.
-- These columns support the full delivery lifecycle:
--   - delivered_at / completed_at: delivery timestamps
--   - download_confirmed_at: attorney confirmed download
--   - urls_invalidated_at: when signed URLs were revoked
--   - zip_storage_path: path to packaged ZIP in Supabase Storage
--   - signed_urls: JSONB array of signed URL records
--   - signed_urls_generated_at / signed_urls_expire_at: URL lifecycle
-- ============================================================================

ALTER TABLE delivery_packages ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMPTZ;
ALTER TABLE delivery_packages ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
ALTER TABLE delivery_packages ADD COLUMN IF NOT EXISTS download_confirmed_at TIMESTAMPTZ;
ALTER TABLE delivery_packages ADD COLUMN IF NOT EXISTS urls_invalidated_at TIMESTAMPTZ;
ALTER TABLE delivery_packages ADD COLUMN IF NOT EXISTS zip_storage_path TEXT;
ALTER TABLE delivery_packages ADD COLUMN IF NOT EXISTS signed_urls JSONB;
ALTER TABLE delivery_packages ADD COLUMN IF NOT EXISTS signed_urls_generated_at TIMESTAMPTZ;
ALTER TABLE delivery_packages ADD COLUMN IF NOT EXISTS signed_urls_expire_at TIMESTAMPTZ;

COMMENT ON COLUMN delivery_packages.signed_urls IS
  'JSONB array of { key, url } objects. Generated by Fn2 handleApprove.';
COMMENT ON COLUMN delivery_packages.signed_urls_expire_at IS
  'When signed URLs expire. Default 7 days from generation.';
